### ISSUE TITLE
Issue with Eucast Expert Rules (Stenotrophomonas maltophilia and CAZ)

### ISSUE THREAD

**Issue by remi-leguern** [msberends/AMR#1]
Using the function eucast_rules(), Stenotrophomonas maltophilia isolates should not be interpreted "R" to ceftazidime.

Indeed, it was updated in v3.1 of EUCAST Expert Rules ( http://www.eucast.org/fileadmin/src/media/PDFs/EUCAST_files/Expert_Rules/Expert_rules_intrinsic_exceptional_V3.1.pdf ) :
"Table 2: Ceftazidime R deleted for Stenotrophomonas maltophilia"

Anyways, thank you a lot for your work. This package is very useful to analyze antimicrobial resistance data.

**Comment by msberends** [comment]
That's completely true, thanks for the catch! Fixing this right away.

**Comment by msberends** [comment]
Now it keeps quiet 😄 

```r
eucast_rules(data.frame(mo = "S. maltophila",
                        cefta = "S"))
#> NOTE: Using column `mo` as input for `col_mo`.
#> NOTE: Auto-guessing columns suitable for analysis...
#> NOTE: Using column `cefta` as input for `CAZ` (ceftazidime).
#
# (...)
#
#> -----------------------------------------------------------------
#> EUCAST rules affected 0 out of 1 rows, making a total of 0 edits
#> => added 0 test results
#> => changed 0 test results
#> -----------------------------------------------------------------
```

This was fixed [here to be precise](https://github.com/msberends/AMR/commit/3e5ab53209268b84163c34676706608463767092#diff-19486c69b49c3c8fdcf665e230918dff). Thanks again.

**Comment by remi-leguern** [comment]
Thank you for your help.

Best wishes,

Rémi
