### ISSUE TITLE
as.sir function not found

### ISSUE THREAD

**Issue by arsp-dev** [msberends/AMR#101]
Hi,

im trying to follow the guide on this link https://msberends.github.io/AMR/articles/WHONET.html but it throws a error 'Error in is_fun_list(.funs) : object 'as.sir' not found'

![image](https://user-images.githubusercontent.com/110375480/225545148-a86ebdc8-5bca-46f4-83a8-af6cb2f849c5.png)

can anyone help me with this. Thank you!

**Comment by msberends** [comment]
Hi, thanks for reaching out!

The `as.sir()` function is part of AMR v2.0, which was released last week. The website reflects the last version (as can also be seen at the left top of the website. The solution is simple:

```r
install.packages("AMR")
```

This will install the latest version. Remember to also load the library when you start the analysis:

```r
library(AMR)
```

Let me know if this helps!

**Comment by arsp-dev** [comment]
Hi @msberends thank you for helping. it works! i will now close this thread
