### ISSUE TITLE
typo in function name in tutorial for "Predicting future antimicrobial resistance using regression models"

### ISSUE THREAD

**Issue by send2dan** [msberends/AMR#111]
RE: typo in function name in tutorial for "Predicting future antimicrobial resistance using regression models"

@ https://msberends.github.io/AMR/articles/resistance_predict.html

e.g. 
```
# choose for error bars instead of a ribbon
ggplot_sir_predict(predict_TZP, ribbon = FALSE)
```

should be
```
# choose for error bars instead of a ribbon
ggplot_rsi_predict(predict_TZP, ribbon = FALSE)
```

This typo in the function name is repeated several times over in the tutorial.

As always, thanks for this amazing package!

**Comment by msberends** [comment]
It is, and not without reason 😄

We changed all mentions of ‘rsi’ to ‘sir’ in AMR v2, which was released last March. See our Changelog: https://msberends.github.io/AMR/news/index.html#sir-vs-rsi-2-0-0

The old functions are still functional, and will remain so for a while. If you use them, you’ll get a warning that they are replaced. So I assume you’re on an older version then?

**Comment by send2dan** [comment]
Thanks for the link! I use multiple PCs for my work in R, and use the {renv} package. Definitely guilty of avoiding updating packages where possible to avoid breaking changes, but I can see here that you have made lots of improvements, making the update worth it!

Best wishes,

Dan

**Comment by msberends** [comment]
No problem! Yes, it's surely worth it I think 😄 

I you run into anything, please let us know!
