### ISSUE TITLE
Errors in CLSI interpretation

### ISSUE THREAD

**Issue by a-cienfuegos** [msberends/AMR#123]
There are some errors in the clinical breakpoint CLSI interpretation. Eg. In E. coli MIC=16 is interpreted as S instead I. I checked the dataset and the susceptible breakpoint was set at 16 instead of 8. Can you correct this issue?

**Comment by msberends** [comment]
Hi, many thanks for bringing this up! We'll look into it. Do you happen to have a screenshot of the CLSI 2023 table where Gram-negatives (or at least, E. coli) is mentioned? And which antibiotic do you mean?

**Comment by a-cienfuegos** [comment]
Hi Dr. Berends, I attached a screenshot of the CLSI 2023 (Table 2A) and the clinical breakpoints table from the AMR package. The antibiotic is ampicillin-sulbactam. Thanks for your help.

[CB.pdf](https://github.com/msberends/AMR/files/12803997/CB.pdf)

**Comment by msberends** [comment]
Hi, many thanks for finding this. It appeared to be an error in the WHONET interpretation files that we used. We'll let them know.

Best,
Matthijs
