### ISSUE TITLE
two genera/species that I can't seem to be able to classify using as.mo()

### ISSUE THREAD

**Issue by send2dan** [msberends/AMR#131]
There are two genera/species that I can't seem to be able to classify using as.mo()

Both fungi

Lomentospora (Previously Scedosporium) & 
Kluyveromyces (a yeast)

**Comment by msberends** [comment]
Great, thanks for letting me know. I was just updating the microorganisms data set, so I’ll be sure to include them.

**Comment by msberends** [comment]
Will be done as part of #135

**Comment by msberends** [comment]
Closing this as completed, please comment on #135 if any change is needed. Thanks!
