### ISSUE TITLE
Incorporate EUCAST 13 and 14

### ISSUE THREAD

**Issue by msberends** [msberends/AMR#137]

**Comment by msberends** [comment]
https://www.eucast.org/clinical_breakpoints

**Comment by msberends** [comment]
PK/PD are left out of EUCAST 14 - another headache. Think about this later.

**Comment by Vincent-AC** [comment]
Hi Matthijs ! Thank you (and all contributors) for this very nice package. I have used it for a litterature review [code here](https://github.com/atb-models-review/atb-models-review.github.io) it was of great help.

Now, I would like to use it again, to automatically compute the EUCAST Susceptible/Resistant status based on our MIC results. Thus I would be glad to help you with the task of incorporating EUCAST 13 and 14 into the package, but even after looking around a bit, I could not find the script that you used to convert the previous EUCAST xlsx files into Rda format, would you agree to share it ? 
Best regards,
Vincent

**Comment by msberends** [comment]
Dear Vincent,

Wow, that’s great! Looks very nice, what a nice idea to create such a webapp, and even nicer that our package could be of help :)

Sure, I share anything I can here. There’s nothing held back, but I’m afraid there is no script to transform the XLSX files. We import breakpoints from WHONET, and do the additional rules manually (such as about expected phenotypes). EUCAST 13 (2023) is already in our breakpoint table `clinical_breakpoints`, but EUCAST 14 (from last January) not yet. The script to get those breakpoints is here: [`data-raw/reproduction_of_clinical_breakpoints.R`](https://github.com/msberends/AMR/blob/main/data-raw/reproduction_of_clinical_breakpoints.R).

The file to add the additional rules is here: [`data-raw/eucast_rules.tsv`](https://github.com/msberends/AMR/blob/main/data-raw/eucast_rules.tsv).

Perhaps you could check if WHONET has EUCAST 14 implemented already? And I would love to work together on that `eucast_rules.tsv` file, it’s always a pain…

**Comment by Vincent-AC** [comment]
Thanks for the quick response ! EUCAST 14 is not in WHONET yet, I'll keep checking occasionally. 

For the eucast_rules.tsv file I haven't checked it in detail yet, is there any work to do on it before implementing EUCAST 14 ? If not, I will still have a look at the EUCAST 14 xlsx and perhaps find new rules to implement in the tsv file when WHONET releases version 14. 

As a side-note have you ever approached the team behind WHONET to know whether they process the xlsx files from EUCAST or if their data comes directly from EUCAST ?

**Comment by msberends** [comment]
Ah okay, thanks for checking. Yes, there is some manual work involved still. The ‘extra’ rules from the Excel files need to be put in the TSV file. With that I mean all non-breakpoint rules. So that’s still some work. 

> As a side-note have you ever approached the team behind WHONET to know whether they process the xlsx files from EUCAST or if their data comes directly from EUCAST ?

Yes, we have. In a collaborative meeting with EUCAST, CLSI, WHO, and WHONET, it was made clear that they process files manually (PDF and Excel). We are in a working group to make this easier from the EUCAST and CLSI side, but this will take some time. So for now, it’s manual work.

**Comment by msberends** [comment]
Just incorporated the EUCAST 14 breakpoints, will be tested as part of [AMR 3.0](https://github.com/msberends/AMR/milestone/2).
