### ISSUE TITLE
MIssing/extra veterinary breakpoints

### ISSUE THREAD

**Issue by samueljpearce** [msberends/AMR#143]
As mentioned in issue #141, the feline E. coli urinary tract breakpoint for ampicillin is missing from the clinical breakpoints dataset, even though it is in the 2023 CLSI VET01S document.

I have just found that the clinical breakpoints dataset contains an extra breakpoint for dogs for Staphylococcus spp. and amoxicillin-clavulanate for urinary tract infections that does not exist in the 2023 CLSI VET01S document. These breakpoints are higher than the combined soft tissue and urinary tract infection breakpoint in the document.

**Comment by samueljpearce** [comment]
Cefazolin for Pasteurella multocida in dogs is also incorrectly given urinary and genital tract sites (should only be for skin, soft tissue and respiratory).

**Comment by msberends** [comment]
> As mentioned in issue https://github.com/msberends/AMR/issues/141, the feline E. coli urinary tract breakpoint for ampicillin is missing from the clinical breakpoints dataset, even though it is in the 2023 CLSI VET01S document.

<img width="1295" alt="image" src="https://github.com/msberends/AMR/assets/31037261/d0a2ca58-a12f-4398-9a17-f0a777f5a3b1">

Apparently it is in the CLSI 2024 data that we imported from WHONET, but not in older guidelines. I'll check the other ones too.

**Comment by samueljpearce** [comment]
Okay, well at least the new ones are correct Strange that the 2023 one is combined UTI/SST infection because they are completely separate with different breakpoints in the VET01S document from 2023.

**Comment by msberends** [comment]
Since we rely on WHONET here, we can only hope that they will add these older (<= 2023) breakpoints as well in a future update.

All other (missing) veterinary breakpoint issues will be addressed in #165. Almost ready for AMR v3.0!
