### ISSUE TITLE
AMR

### ISSUE THREAD

**Issue by Samuel-Vinicius** [msberends/AMR#145]
For study  purpouses

**Comment by msberends** [comment]
Can I help you with this? This is not a well-formulated issue at the moment :)

**Comment by Samuel-Vinicius** [comment]
> Can I help you with this? This is not a well-formulated issue at the moment :)

Sorry, it was a misunderstanding, i was thinking it was a survey, i'm not very good at the functioning of github, sorry for spending your time.

**Comment by msberends** [comment]
No problem!
