### ISSUE TITLE
Not all mo_transforms work with antibiogram

### ISSUE THREAD

**Issue by andrewjmc** [msberends/AMR#148]
I think line 297 of antibiogram.r should read

``x$`.mo` <- mo_property(x$`.mo`, property=mo_transform, language = language)``

rather than

``x$`.mo` <- mo_property(x$`.mo`, language = language)``

Currently transforms are not supported other than those hardcoded!

Thanks,

Andrew

**Comment by msberends** [comment]
My goodness! You’re absolutely right!! I’ll fix it right away today, thanks so much for letting know!
