### ISSUE TITLE
Incorrect reporting of R e.g CIP and Enterobacterales?

### ISSUE THREAD

**Issue by antunderwood** [msberends/AMR#15]
The EUCAST breakpoint table for CIP and Enterobacterales shows
![image](https://user-images.githubusercontent.com/423/93306998-7380ea80-f7f8-11ea-93bb-b84e80ce78d6.png)
This is replicated in you rsi_translation data
![image](https://user-images.githubusercontent.com/423/93307214-a4611f80-f7f8-11ea-940f-f221ac5d8545.png)
However this code yields R
```
> as.rsi(x = as.mic(0.5),
        mo = as.mo("E. coli"),
        ab = "CIP",
        guideline = "EUCAST")
=> Interpreting MIC values of `CIP` (ciprofloxacin) using guideline EUCAST 2020 ... OK.
Class <rsi>
[1] R
```
I would have expected this to be I

**Comment by antunderwood** [comment]
I also see similar for Meropenem

![image](https://user-images.githubusercontent.com/423/93312430-1dfc0c00-f7ff-11ea-8e91-5ecec6981d7c.png)
```
> as.rsi(x = as.mic("8"),
+        mo = as.mo("E. coli"),
+        ab = "Meropenem",
+        guideline = "EUCAST",
+        conserve_capped_values = T)
=> Interpreting MIC values of `Meropenem` (MEM, meropenem) using guideline EUCAST 2020 ... OK.
Class <rsi>
[1] R
```

**Comment by msberends** [comment]
Right! This is because the "<= S" and ">R". We now interpret it using <= S" and ">=R". So the MIC of 0.5 in this example:

> ```r
> as.rsi(x = as.mic(0.5),
>        mo = as.mo("E. coli"),
>        ab = "CIP",
>        guideline = "EUCAST")
> ```

matches the value in `rsi_translation$breakpoint_R`.

Nice catch! Needs an immediate fix!

**Comment by antunderwood** [comment]
As far as I can tell for EUCAST, all MIC breakpoints are reported as `S <= X` and  `R > Y`

**Comment by msberends** [comment]
Solved in https://github.com/msberends/AMR/commit/4e40e42011b5e16b2f0c7f4ffd206a4e8efa9b1d

**Comment by antunderwood** [comment]
Thanks for fixing this. Will you be making a new release tag with this fix?

**Comment by antunderwood** [comment]
Thanks for fixing this. Will you be making a new release tag with this fix?

**Comment by msberends** [comment]
Yes! We are in the final phase of sending a new version of this package and its manuscripts to our reviewers, so I expect it to release another CRAN version in approximately two weeks.

**Comment by antunderwood** [comment]
Great news about the the manuscript. If they ask for reviewers, I'd be happy to be considered
