### ISSUE TITLE
as.sir reports invalid results as coming from wrong columns

### ISSUE THREAD

**Issue by andrewjmc** [msberends/AMR#150]
Hello,

Sorry not to have a reproducible example to share, but I found that as.sir told me about two columns with inappropriate values. 

`in as.sir(): 77 results in column 'Minocycline' truncated (0%) that were invalid antimicrobial interpretations: "N", "P", and "PP" `

However, on inspection the columns with the inappropriate values were actually near adjacent (+1 and +2 in each case). I wonder if the function is making a small error in the logic to pull out the column names.

Best wishes,

Andrew

**Comment by msberends** [comment]
I’ll look into it! Could you share the column names you have?

**Comment by andrewjmc** [comment]
Actually in trying to rerun it to make it do the same it hasn't failed. I wondered if it was due to previously duplicated antibiotic columns [e.g. Gentamicin (Low) and Gentamicin (High)] but that doesn't seem to be the case. I'll close and if I see it again investigate in more detail!
