### ISSUE TITLE
Add denominators to each antibiotic in antibiogram

### ISSUE THREAD

**Issue by andrewjmc** [msberends/AMR#153]
I have another suggestion. Sometimes one might wish to add raw denominator (and/or numerator) data to an antibiogram for each result. It might be verbose, but could be used for some downstream processing.

I tested a small hard-coded modification to the antibiogram code, with success except for the use of the digits parameter (I must have misunderstood some context). It would be little addition to have a parameter like `raw_n` with default `NA` and possible values of "N/D" and "D".

I'll be interested in your thoughts!

<code>
function (x, antibiotics = where(is.sir), mo_transform = "shortname", 
  ab_transform = NULL, syndromic_group = NULL, add_total_n = TRUE, 
  only_all_tested = FALSE, digits = 0, col_mo = NULL, language = get_AMR_locale(), 
  minimum = 30, combine_SI = TRUE, sep = " + ", info = interactive()) 
{
...
  out <- out %pm>% pm_summarise(SI = paste0(round(numerator * 
    100/total, digits = digits), "% (", total, ")"))
...
  long_to_wide <- function(object, digs) {
    #object$SI <- round(object$SI * 100, digits = digs)
...
}

</code>

**Comment by msberends** [comment]
Yes, that's a nice idea. They are 'kind of' added already at the moment, where I for the implementation followed [this table from a recent paper](https://journals.sagepub.com/doi/10.1177/20499361211011373#table2-20499361211011373) to present the data. It's also shown [in our manual](https://msberends.github.io/AMR/reference/antibiogram.html#ref-examples):

<img width="665" alt="image" src="https://github.com/msberends/AMR/assets/31037261/cc59d090-5455-4c8d-81a9-c0e8b20dba08">

The first column contains the denominators, but that can of course be different per antibiotic. That's not optimal. Where would you want to present the D or N/D then? Perhaps instead of the %SI?

**Comment by andrewjmc** [comment]
Thanks, I had noted the ability to provide in aggregate. In the example I gave I have presented by appending to the %SI, e.g. `6` becomes `6% (6/100)`. But it could be implemented with flexibility to provide denominators only, e.g. `6% (100)`. Alternative approaches could duplicate columns (e.g. `AMK %` and `AMK n/d`) or rows (e.g. `CoNS %` and `CoNS n/d`).

For me, I'm thinking of it more for downstream processing than for presentation - i.e. could be included as a hover detail in a plotly chart. There are use cases for presentation. If it is provided in a structured way, users can post-process to present richly-formatted tables (e.g. present the denominator in a small font size, different colour).

**Comment by msberends** [comment]
Awesome suggestion, implemented it today. Please see [`antibiogram()` > Details > Formatting Type](https://msberends.github.io/AMR/reference/antibiogram.html#formatting-type) where you will find 12 options to set the formatting of all 'cells':

---

![image](https://github.com/user-attachments/assets/4e7fd5c4-143f-4930-a9fd-6c6657d721de)

---

You might be interested in the raw values if you use it for presentation or other forms downstream, by running `attributes(x)$out_numeric` where `x` is the outcome of `antibiogram()`.

```r
x <- antibiogram(example_isolates,
                 antibiotics = c(aminoglycosides(), carbapenems()))
attributes(x)$out_numeric
#>                mo         ab percentage numerator total
#> 1            CoNS   Amikacin  0.0000000         0    43
#> 2            CoNS Gentamicin  0.8640777       267   309
#> 3            CoNS   Imipenem  0.5208333        25    48
#> 4            CoNS  Kanamycin  0.0000000         0    43
#> 5            CoNS  Meropenem  0.5208333        25    48
#> 6            CoNS Tobramycin  0.2181818        12    55
#> 7         E. coli   Amikacin  1.0000000       171   171
#> 8         E. coli Gentamicin  0.9804348       451   460
#> 9         E. coli   Imipenem  1.0000000       422   422
#> 10        E. coli  Meropenem  1.0000000       418   418
#> 11        E. coli Tobramycin  0.9740260       450   462
#> 12    E. faecalis   Amikacin  0.0000000         0    39
#> 13    E. faecalis Gentamicin  0.0000000         0    39
#> 14    E. faecalis   Imipenem  1.0000000        38    38
#> 15    E. faecalis  Kanamycin  0.0000000         0    39
```

Although this is more or less the outcome of `bug_drug_combinations()`, which `antibiogram()` uses internally.

**Comment by andrewjmc** [comment]
Super, that's a really well thought out and full featured implementation! I will pull the latest into my project ASAP!

**Comment by msberends** [comment]
Many thanks!
