### ISSUE TITLE
Error when antibiogram empty

### ISSUE THREAD

**Issue by andrewjmc** [msberends/AMR#156]
Hello,

It appears that if antibiogram cannot produce any rows (e.g. due to no taxa crossing the `minimum` threshold) there is an error.

Is this intentional, or would an empty table + a warning be intended?

Traceback

```
8: (function (..., na.last = TRUE, decreasing = FALSE, method = c("auto", 
       "shell", "radix")) 
   {
       z <- list(...)
       decreasing <- as.logical(decreasing)
       if (length(z) == 1L && is.numeric(x <- z[[1L]]) && !is.object(x) && 
           length(x) > 0) {
           if (.Internal(sorted_fpass(x, decreasing, na.last))) 
               return(seq_along(x))
       }
       method <- match.arg(method)
       if (any(vapply(z, is.object, logical(1L)))) {
           z <- lapply(z, function(x) if (is.object(x)) 
               as.vector(xtfrm(x))
           else x)
           return(do.call("order", c(z, list(na.last = na.last, 
               decreasing = decreasing, method = method))))
       }
       if (method == "auto") {
           useRadix <- all(vapply(z, function(x) {
    ...
7: do.call(order, lapply(pm_groups, function(x) res[, x]))
6: pm_summarise.grouped_data(.data, ...)
5: pm_summarise(out, SI = numerator/total)
4: eval(as.call(c(rhs[[1L]], lhs, as.list(rhs[-1L]))), envir = parent.frame())
3: eval(as.call(c(rhs[[1L]], lhs, as.list(rhs[-1L]))), envir = parent.frame())
2: out %pm>% pm_summarise(SI = numerator/total)
1: antibiogram call
```

**Comment by msberends** [comment]
Errors are never intended 😄 

Appears to be an ordering error, your error text in 8 is the literal text of the `order()` function of R itself. I'll look into it!

**Comment by msberends** [comment]
Found it already. In AMR v3.0, it will show and return like this (I added a nice header and footer for those who have `tibble` installed 😛).

---- 

Normal behaviour, enough rows to show something:

<img width="886" alt="image" src="https://github.com/msberends/AMR/assets/31037261/b5190654-7ddd-4c04-9d62-ed4819918a62">

---- 

Behaviour when the result is an empty data set:

<img width="888" alt="image" src="https://github.com/msberends/AMR/assets/31037261/68c910ca-de15-4a7f-8b5d-a26443c117f7">


----

**Comment by msberends** [comment]
Many thanks for pointing this out!

**Comment by andrewjmc** [comment]
That's great, thanks for the speedy fix!
