### ISSUE TITLE
Teleomorph vs anamorph ID of yeasts

### ISSUE THREAD

**Issue by send2dan** [msberends/AMR#157]
Hello, 

as.mo() struggles a bit with yeasts. 

Some yeasts may have two names that correlate to the growth state of the fungus: an anamorph name associated with asexual growth and replication (mitosis only) of the fungus and a teleomorph name associated with the sexual growth and replication. Examples of dual names are listed in the reference below [1]. 

Notably, for many yeasts the MALDI-TOF now only reports the teleomorph name, which may not include "Candida" even though the organism can be reasonably classified to that genus [1]. 

In practice, in Newcastle, since approx. Aug 2023, the MALDI-TOF has never once reported e.g. Candida lusitaniae or Candida krusei, but has continued to report e.g. Candida albicans and Candida parapsilosis. 

While CLSI recommends using the anamorph name (e.g., "Candida krusei") for common fungi in reports due to clinician preference [1], MALDI-TOF's innate reporting of the teleomorph presents a practical challenge. At some stage, the teleomorph name given by the MALDI-TOF needs to be changed to the anamorph name (e.g. Pichia kudriavzevii changed to Candida krusei).

Can the AMR package be updated to reflect alternate names for select Candida species/yeast?

Teleomorph name	Anamorph name
Wickerhamomyces anomalus	Candida pelliculosa
Clavispora lusitaniae	Candida lusitaniae
Meyerozyma guilliermondii	Candida guilliermondii
Kluyveromyces marxianus	Candida kefyr
Pichia kudriavzevii	Candida krusei
Pichia caribbica/Meyerozyma caribbica	Candida fermentati
Kodamaea ohmeri	Candida guilliermondii var membranifaciens
Yarrowia lipolytica	Candida lipolytica
Cyberlindnera fabianii	Candida fabianii
Debaryozyma hansenii	Candida famata
Pichia fermentans	Candida lambica
Pichia norvegensis	Candida norvegensis
Cyberlindnera jadinii	Candida utilis

References
[1] [https://www.cdc.gov/candidiasis/hcp/anamorph-and-teleomorph-names/index.html](https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cdc.gov%2Fcandidiasis%2Fhcp%2Fanamorph-and-teleomorph-names%2Findex.html&data=05%7C02%7Cdweiand%40nhs.net%7Cd4274f503a8a4b139c2a08dca0de5e40%7C37c354b285b047f5b22207b48d774ee3%7C0%7C0%7C638562124118306918%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=JhOhz802vwT9EbUF9ftpFURa5MZC8sQEOwwRqWiHvHk%3D&reserved=0)

**Comment by send2dan** [comment]
Noted #135 may help answer my request here, thanks :)

**Comment by msberends** [comment]
Ahhh, I think you are -really- going to like the update I’ve been working on for the past 4-6 weeks! I’m currently implementing [MycoBank](https://www.mycobank.org/) that has both teleomorph name anamorph names available. Though sadly enough, they don’t register which are which in a structured way, but keep rather standardised taxonomic status names. 

Take for example their query page (https://www.mycobank.org/Simple%20names%20search) and type in “Candida krusei”. You’ll see that they consider Pichia as its ‘current name’. I’m currently exploring the best ways to implement all useful details. 

First indications show that the AMR package will gain about 10,000 new fungi and the latest taxonomic info on existing ones. 

I’ll try to wrap it up over the next weeks. It’s in my ‘spare’ working hours, but I’ll have a lot more of them now that colleagues start to go on holidays :)

For this topic, and especially for your expertise regarding this topic, we perhaps could have a video call? That would probably help me better in choosing the right angles which this complex part of microbial taxonomy. I’ve always been more of a bacteriologist to be frank 😊

**Comment by send2dan** [comment]
Thanks Matthijs, happy to help if you want a second opinion on this subject – I’ve been away on leave a bit myself, but will be fully up and running again from 9/9/24.

**Comment by msberends** [comment]
Closing this as completed, please comment on #135 if any change is needed. Thanks!
