### ISSUE TITLE
scale_x_mic not working

### ISSUE THREAD

**Issue by theanita1** [msberends/AMR#160]
Previously I had the scale_x_mic working but today it seems not to want to work. I thought it was my new coding, so I went back to my previous report script files and ran those codes as is and the function isn’t working then. Between then (March 2024) and now I have updated the package to the current beta version on github. I uninstalled the beta version, going back to the CRAN version (2.1.1), but then R stated that the function doesn’t even exist. 
 
Have attached provided images of the output where I managed to have it working previously (March 2024), and what I have now (July 2024). 
 
Here is my current coding for my charts, noting that I have it wrapped in a function because I have so many charts in my reports. Nothing has changed between March and now. I appreciate a lot of my code is formatting for the particular aesthetic required for my reports. The scale_y_continuous coding is how I transform my charts from counts to proportions (as I mention in my other post for the scale_y_percent function)
 
```
#function
mic_graph<- function(mic_dat, organism, antibiotic){ autoplot(mic_dat, mo = {{organism}}, ab = {{antibiotic}}, guideline = "EUCAST 2022", include_PKPD = F, ylab = translate_AMR("Proportion"), expand = T)+
    theme_classic()+ theme(legend.position.inside = c(.95, .95), legend.justification = c("right", "top"))+ ggtitle("")+ scale_x_mic()}
 
#plot in image
mic_graph(salm_mic_1$CIP, "Salmonella", "Ciprofloxacin")+ ggtitle("", subtitle  = "2013 - 2015") +
  scale_y_continuous(labels = function(x) paste0(round(x/65*100,1), "%"), breaks = seq(0, 65, 16.25),
                     expand = expansion(mult = c(0, 0.1)), limits = c(0, 65)) + scale_x_mic(mic_range = c(0.06, 4))

```
**What it should look like** 
![salm_fluro_mic](https://github.com/user-attachments/assets/5b9d5462-52aa-45f1-b141-a707a3948157)
**What the code is currently producing**
![salm_fluro_mic_wrong](https://github.com/user-attachments/assets/46277c01-e2a4-4c57-bf8a-3b7b21dabda5)

**Comment by msberends** [comment]
Thanks for finding this bug and reporting it! I’ll have a look into it - that scale function should work as you expect.

**Comment by msberends** [comment]
This is now fixed in the latest beta version.

It was not possible (anymore) to set a MIC range outside the input range (e.g., have data running from 0.5 to 2, and setting `mic_range = c(0.0625, 4)`). This is now fixed.
