### ISSUE TITLE
suppress information 'warning'  with as.mo  mo_gramstain  etc

### ISSUE THREAD

**Issue by iDudeRPS** [msberends/AMR#161]
hai

is it possible  (temporary) suppress the info that is printed to the console when using as.mo etc.

I very much appreciate the info, but not every time..

**Comment by msberends** [comment]
Set `info = FALSE`, like this:

```r
as.mo("Enterobacter aerogenes", info = FALSE)
#> Class 'mo'
#> [1] B_KLBSL_AERG
```


From the docs: https://msberends.github.io/AMR/reference/as.mo.html#arg-info

> **info**
a [logical](https://rdrr.io/r/base/logical.html) to indicate if a progress bar should be printed if more than 25 items are to be coerced - the default is `TRUE` only in interactive mode

**Comment by msberends** [comment]
That explanation is not saying that old taxonomic will not be printed, I'll update that!
