### ISSUE TITLE
Turn off information as.mo  mo_gramstain etc

### ISSUE THREAD

**Issue by iDudeRPS** [msberends/AMR#162]
Hai

Is there a possibility to turn of the information and or warnings that are given by amr?
I appreciate the information   but i do not want to read the info everytime  when using as.mo

**Comment by msberends** [comment]
This is duplicate of #161 that you opened yesterday it seems? Let me know if it wasn’t. 

In short, you’ll want `info = FALSE`.

**Comment by iDudeRPS** [comment]
yes duplicate. sorry

**Comment by msberends** [comment]
No problem!
