### ISSUE TITLE
Some organisms not in database

### ISSUE THREAD

**Issue by theanita1** [msberends/AMR#164]
Hi Mathjis

Have a sample in my dataset (different dataset to previous) that have a few patients with organisms not in the database
- _Epidermophyton floccosum_ --> whilst I can find other Arthrodermataceae in the microorganism data, apparently this is the only pathogen in the genus [info source: https://www.adelaide.edu.au/mycology/fungal-descriptions-and-antifungal-susceptibility/dermatophytes/epidermophyton]
- _Quambalaria cyanescens_ --> the suggested synonyms for this are also not in [this list: https://www.adelaide.edu.au/mycology/fungal-descriptions-and-antifungal-susceptibility/hyphomycetes-conidial-moulds/quambalaria]. Another website has one of the synonyms as a [different name: https://drfungus.org/knowledge-base/fugomyces/] that also isn't in the database.
- _Nannizzia gypsea_ --> apparently is the name now for what was _Microsporum gypseum_ [info source: https://www.adelaide.edu.au/mycology/fungal-descriptions-and-antifungal-susceptibility/dermatophytes/nannizzia#nannizzia-gypsea]
- _Syncephalastrum racemosum_--> there are others with the same species name but I can't find anything to suggest synonyms [info source: https://www.adelaide.edu.au/mycology/fungal-descriptions-and-antifungal-susceptibility/zygomycota-pin-moulds/syncephalastrum-racemosum]

Not urgent, but if appropriate maybe they can be added to the list

**Comment by theanita1** [comment]
Some other errors from mo_uncertainties:
- _Chilomastix mesnili_ - the genus and some other species are in the db, but not this species. Instead of transforming to the genus only, the as.mo function transformed this to _Methylobacterium mesophilica_
- There is nothing for _Cryptosporidium_ or _Shistosoma_
---> On this, there is no (unknown protozoa) option
- The input "Sarcoptes scabei" converted to "Streptomyces somaliensis" rather than _Sarcoptes scabiei_ as in the db
- _Sporothrix schenkii_ --> this version of the name isn't in the db but _Sporotrichum_ is. However, the input of this entry was converted to "Staphylococcus schleiferi schleiferi", I think because one of the candidates is "Sporotrichum schenckii" (see highlighted in screenshot of uncertainties)
![image](https://github.com/user-attachments/assets/d38047ad-47d2-4e49-adbb-83519cbbfb9e)

**Comment by msberends** [comment]
Many thanks, this is really helpful. We're working on adding tens of thousands of fungi, and make the package more useful for mycological analyses. This helps, hopefully they will all be added by our new source: MycoBank. I'll check the species you've put here though.

**Comment by msberends** [comment]
Please see #135. I did check all the ones you mentioned here - they now work!

One exception: *Chilomastix mesnili* cannot be found and it thus not in the GBIF database that we use for all non-bacteria and non-fungi - it is a protozoan. But at least, now this happens:

```r
AMR::as.mo("Chilomastix mesnili")
#> ℹ Microorganism translation was uncertain for "Chilomastix mesnili" (assumed Chilomastix motellae). Run mo_uncertainties() to review this, or use
#>   add_custom_microorganisms() to add custom entries.
#> Class 'mo'
#> [1] P_CHLMS_MTLL
```

Seems fair.

Plus, there's now a code for an unknown species of the Protozoa kingdom, that you suggested:

```r
AMR::mo_name("P_PROTOZOAN")
#> [1] "(unknown protozoan)"
```

Many thanks for your suggestions!

**Comment by msberends** [comment]
Closing this as completed, please comment on #135 if any change is needed. Thanks!
