### ISSUE TITLE
as.sir() hangs in latest beta if unknown column present

### ISSUE THREAD

**Issue by samueljpearce** [msberends/AMR#166]
I'm not sure where this bug has come from as I'm fairly sure it worked fine before updating to the latest beta. My dataset has some columns unrelated to the MICs (e.g. testing date, lab ID). For some reason, using as.sir() in this version just hangs if these columns are not removed. The same goes for the first_isolate column.

Do correct me if I am wrong, but I think this worked fine with unrelated variables prior to this beta version. I always removed these prior to the antibiogram creation but after SIR interpretation.

**Comment by msberends** [comment]
Can you post me your columns names? I assume that's not soo sensitive information? Should indeed work fine, might be caused by something else. If you could provide a kind of minimal reproducible example, that would be awesome.

**Comment by samueljpearce** [comment]
The data frame is as follows:
- date
- id
- host
- specimen
- ward
- organism
- Followed by antibiotics/MICs
- First isolate

It is the same dataset that I used before updating to the latest beta with no issues prior. Similar to the minimal example I used here https://github.com/msberends/AMR/issues/141#issuecomment-2000427647

**Comment by msberends** [comment]
I cannot replicate it with the latest beta (2.1.1.9080). I think this is solved, as I had previous problems with the `uti` argument that also seems to cause this problem.

Please check again if it still happens, then I'll reopen this issue.
