### ISSUE TITLE
About Antibiogram

### ISSUE THREAD

**Issue by lingbingzeng1985** [msberends/AMR#169]
Hello,
When I used the antibiogram, I found the package installed by R script did not have the parameter "formatting_type". Would you like to solving the problem? Thanks.
Lingbing

**Comment by msberends** [comment]
Hi,

That’s right, it’s only available in the beta version at the moment. You can install that like this:

```r
install.packages("AMR", repos = "https://msberends.r-universe.dev")
```

We expect to release a new version around next month.
