### ISSUE TITLE
Custom guideline for as.rsi()

### ISSUE THREAD

**Issue by yomac98** [msberends/AMR#17]
Hello! Thank you for this useful tool! 
I was wondering if there is a way to have a customary guildeline in as.rsi(). It may be because my data is from veterinary field, but I get too many NAs and even different breakpoints applied with the current 'EUCAST' or 'CLSI' guildeline implemented in the package. So it'll be really great if I can have "my breakpoints" in the rsi_translation file and call it when using as.rsi(). 
Thank you! :D

**Comment by msberends** [comment]
Thanks for coming up with this idea! 

Can you give me perhaps a code example? I like the idea of making it more flexible.

**Comment by yomac98** [comment]
No, I don't have any example code (I'm still a novice at R). The way I thought it could go is that I make my own breakpoint file in the format of the 'rsi_translation' file and call it "manual", and have a function to use it in as.rsi( guideline="manual").

**Comment by msberends** [comment]
Good point, I'm almost finished implementing your wish 😄

**Comment by msberends** [comment]
Alright, please see here for reference: https://msberends.github.io/AMR/reference/as.rsi.html

You can now use `as.rsi(..., reference_data = ...)`. If you set `reference_df`, the `guideline` parameter will be ignored.

Please try it! You can install the beta version that contains this enhancement with:

```r
install.packages("remotes")
remotes::install_github("msberends/AMR")
```

You might need to restart R for it to take effect.

**Comment by msberends** [comment]
### 📋 Please take part in our survey!
Now you're at it, please fill in [our short questionnaire](https://msberends.github.io/AMR/survey.html)! You can fill it in completely anonymously. If you know others using this `AMR` package, please ask them to fill it in too. 

Your valuable input will help to improve the package and its functionalities 🙂

**Comment by yomac98** [comment]
This works beautifully! Thank you so much for your prompt, wonderful response/work! 👍 💯

**Comment by msberends** [comment]
👍
