### ISSUE TITLE
Commented line causes initialization to fail

### ISSUE THREAD

**Issue by advoropaev** [msberends/AMR#172]
Line "import importlib.metadata as metadata" is commented somewhy in datasets.py.

**Comment by msberends** [comment]
I’ll check it. Package data should be in this repo too btw. I’ll add it.

**Comment by msberends** [comment]
This is fixed now, see here:

https://github.com/msberends/AMR/blob/059618e710d2f54a360536710a4cd42f54498401/PythonPackage/AMR/AMR/datasets.py#L10
