### ISSUE TITLE
issue with as.ab  (amr 1.5)

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#20]
hai

this code works under AMR 1.4, but not with AMR 1.5:

df <- df %>% rename_with(df, .fn =  as.ab, .cols = amikacine:voriconazol)

now with AMR 1.5 I get this error:

Error: in .fn(): argument `flag_multiple_results` must be of class "logical", not "tbl_df/tbl/data.frame"

(greetings, 
Rogier)

**Comment by msberends** [comment]
Thx! I’ll look into it.

**Comment by msberends** [comment]
The error was caused because of a syntactic error at your side I'm afraid 🙂 

You wrote
```r
df <- df %>% rename_with(df, .fn = as.ab, .cols = amikacine:voriconazol)
```

But after a pipe, the data object (`df`) must be omitted, like this:

```r
df <- df %>% rename_with(.fn = as.ab, .cols = amikacine:voriconazol)
# or even shorter
df <- df %>% rename_with(as.ab, amikacine:voriconazol)
```

So the error was right, it said that the second argument of `as.ab()` (which is `flag_multiple_results`) must be `TRUE` or `FALSE`, not a data set.

**Comment by msberends** [comment]
So that it worked under 1.4.0 was erroneous, it was incorrectly allowed.

**Comment by msberends** [comment]
Small idea to make your script independent of variable names (assuming that your variables with AB results are of class `<rsi>`, e.g., using `as.rsi()`):

```r
df <- df %>%
  rename_with(as.ab, where(is.rsi))
```

If they aren't already of class `<rsi>`, you can add this `mutate()`:

```r
df <- df %>%
  mutate(across(where(is.rsi.eligible), as.rsi)) %>%
  # or the good old and way better readable:
  # mutate_if(is.rsi.eligible, as.rsi) %>% 
  rename_with(as.ab, where(is.rsi))
```

**Comment by ghost** [comment]
Thanks!! Also for the suggestions.
This was a slip-up on my part. It now works perfectly
