### ISSUE TITLE
Custom MDRO guidelines 

### ISSUE THREAD

**Issue by msberends** [msberends/AMR#23]
As per #21 :

Support custom guidelines for the `mdro()` function.

**Comment by msberends** [comment]
@jukkiebah What kind of custom rules do you apply at your hospital?

**Comment by ghost** [comment]
the collegues from the infection control department use more specific terminology, based on the level of infection control precautions that are in place. Multi-resistant vs multi-resistant+   etc.  I was just curious. Its not that something that i want to go into at the moment (so little time...)

**Comment by msberends** [comment]
This has been great 😄 Very importing addition to the package, so that's for the idea!

This is now implemented in the latest beta. Please see our website where it is explained already: https://msberends.github.io/AMR/reference/mdro.html#using-custom-guidelines

It basically comes down to this:

```r
# set your own specific rules like you would in dplyr::case_when():
my_hospital_rules <- custom_mdro_guideline(CIP == "R" & age > 60 & is_isolated == TRUE ~ "Modified BRMO 1",
                                           AMX == "R" & age > 90 & is_isolated == TRUE ~ "Modified BRMO 2")

# and run them, by setting the custom rules as the `guidelines` parameter:
your_data %>%
  mudate(BRMO = mdro(guideline = my_hospital_rules))
```
