### ISSUE TITLE
refinement of eucast-ampc rules

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#25]
hai
a refinement that should be made:
the new rule to make the ampc organisms R (or make NA), is based on isolates that show S based on in vitro results. But raw results with 'I' should also be included.  Because of the resistance mechanism, these are essentially the same situations.

eucast text that you quote:

'a character value that should be applied for AmpC de-repressed cephalosporin-resistant mutants, defaults to NA. Currently only works when version_expertrules is 3.2; 'EUCAST Expert Rules v3.2 on Enterobacterales' states that susceptible (S) results of cefotaxime, ceftriaxone and ceftazidime should be reported with a note, or results should be suppressed (emptied) for these agents. A value of NA for this argument will remove results for these agents, while e.g. a value of "R" will make the results for these agents resistant.'  

does not explicitly state this, but it is ofcourse implied.

**Comment by msberends** [comment]
Absolutely! I'm adding `"I"` as well! Just forgot about it :smile:

**Comment by msberends** [comment]
Available in AMR v1.5.0.9012 and later (test with `remotes::install_github("msberends/AMR")`)
