### ISSUE TITLE
ampc cefalosporin resistance

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#28]
hai matthijs

previously you added the (convenient) function to automatically change the cephalosporins resistance for chrom-ampc organisms to R.   We forgot however, that the first and second generations and the penicillins w/o inhibitor also should be made R in these instances.....

gr

Rogier

**Comment by msberends** [comment]
Oops 😳

**Comment by msberends** [comment]
Working on the fix!

**Comment by msberends** [comment]
Thinking about this, isn’t that covered with intrinsic resistance? Such as amox in Enterobacter cloacae? 

I’m not sure if there’s a formal EUCAST rule to force resistance in those ampC mutants for all those drugs you mention.

**Comment by msberends** [comment]
Added a new parameter, `ampc_penicillin_resistance`. Works the same as `ampc_cephalosporin_resistance`, but sets all 1st and 2nd gen cephalos and penicillins without enzyme inhibitor, and defaults to `FALSE`.

This parameter will effect these antibiotics in Citrobacter braakii, Citrobacter freundii, Citrobacter gillenii, Citrobacter murliniae, Citrobacter rodenticum, Citrobacter sedlakii, Citrobacter werkmanii, Citrobacter youngae, Enterobacter, Hafnia alvei, Klebsiella aerogenes, Morganella morganii, Providencia and Serratia:

Amoxicillin
Ampicillin
Apalcillin
Aspoxicillin
Avibactam
Azidocillin
Azlocillin
Aztreonam
Bacampicillin
Benzylpenicillin
Carbenicillin
Carindacillin
Cefacetrile
Cefaclor
Cefadroxil
Cefaloridine
Cefamandole
Cefatrizine
Cefazedone
Cefazolin
Cefmetazole
Cefonicid
Ceforanide
Cefotetan
Cefotiam
Cefoxitin
Cefprozil
Cefroxadine
Ceftezole
Cefuroxime
Cephalexin
Cephalothin
Cephapirin
Cephradine
Ciclacillin
Clometocillin
Cloxacillin
Dicloxacillin
Epicillin
Flucloxacillin
Hetacillin
Lenampicillin
Loracarbef
Metampicillin
Methicillin
Mezlocillin
Nacubactam
Nafcillin
Oxacillin
Penamecillin
Phenethicillin
Phenoxymethylpenicillin
Piperacillin
Piridicillin
Pivampicillin
Pivmecillinam
Propicillin
Sarmoxicillin
Sulbactam
Sulbenicillin
Sultamicillin
Talampicillin
Tazobactam
Temocillin
Ticarcillin

**Comment by ghost** [comment]
hai

thanks. The inhibitor-combinations should also be included in the list. (AMC, PTZ etc)
Not sure of the name of the parameters, is somewhat misleading.  Maybe seperate parameters for penicillines, 1st, 2nd, 3rd generations?   Or ideally wrap them all together in one parameter.  Users that will use this parameter for 3rd gen cephalo will always use it also it the other ones (see also eucast rules). 
An enterobacterales that is  3GC_R , but 2GC_S and/or AMC_S is not very likely.

**Comment by msberends** [comment]
Hm, I’m not sure about this whole addition. I understand your point of view from the pragmatism and the clinic. But the function is called ‘eucast_rules()’, for this package we should only add rules that are obvious, clear and well documented by EUCAST. I’m missing the rules we have discussed here in EUCAST documentation or guidelines. 

I know they make sense if you read Kucers or any other book, but this should really 100% be following EUCAST. Do you know if there’s a published basis for the new rules we discussed here?

**Comment by ghost** [comment]
Hai matthijs
The rules on the the second generation cefalos come from this document (rule5).

The rules on first generation and penicillines come from the intrinsic table (see below)
So, maybe the are already included in the the eucast rules function. I have not checked that...


[eucast tabellen.pdf](https://github.com/msberends/AMR/files/6121242/eucast.tabellen.pdf)
[ExpertRules_V3.2_20190515_Enterobacterales.pdf](https://github.com/msberends/AMR/files/6121243/ExpertRules_V3.2_20190515_Enterobacterales.pdf)

**Comment by msberends** [comment]
Alright. I could work on a `custom_AMR_rules()` function or so, so that EUCAST rules can be expanded with additional organisation-specific rules.

**Comment by msberends** [comment]
#31
