### ISSUE TITLE
Cannot specify column for species designation in mdro()

### ISSUE THREAD

**Issue by jhawkey** [msberends/AMR#33]
Hi,

Thanks for a great package! I had a small issue with the `mdro()` function that I managed to fix, details below.

When I ran the `mdro()` function on my table of SIR phenotypes, I kept getting the following error:
```
> mdro(vitek_spp)
NOTE: Using column 'species' as input for `col_mo`.
Auto-guessing columns suitable for analysis... OK.
Error: Can't convert `species` <character> to match type of `species` <mo>.
```

Running
`mdro(vitek_spp, col_mo = "species")`
threw the same error as above, even though I was specifying which column had the species information.

I also tried converting my species column into the `mo` type:
`vitek_spp <- vitek_spp %>% mutate(species = as.mo(species))` and confirmed that this column was an S3:mo variable type, but still got the same error as above.

Eventually I worked out that if I named my species column, `mo` instead (the same column name as the example_isolates data included with the package), the function would run.

Is this the expected behaviour?

**Comment by msberends** [comment]
Hi Jane, many thanks for using our package!

No, that’s absolutely not the way it should behave. The intended behaviour is that it just works without requiring you to think about it 🙂 

Would you be able to share the structure of your data here, by pasting the output of `str(vitek_spp)`? Feel free to remove the actual data it prints, I’m just curious for the column names and data types. 

I think the problem might be that the `microorganisms` data set also contains a column ‘species’, but that should not pose a problem. Could you also try:

```r
vitek_spp %>%
  rename(mybugs = species) %>%
  mdro()
```

Then my last question, which AMR package version are you using?

**Comment by jhawkey** [comment]
Okay, after running the following command (which converts the species column from character to the mo class, and then displaying the output of `str(vitek_spp)`:
```
vitek_spp <-vitek_spp %>% select(-acquired_esbl) %>% filter(!is.na(AMP)) %>% mutate(species=as.mo(species))
str(vitek_spp)
tibble [403 × 20] (S3: tbl_df/tbl/data.frame)
 $ sampleID: chr [1:403] ...
 $ species : 'mo' chr [1:403] "B_KLBSL_PNMN" "B_KLBSL_PNMN" "B_KLBSL_PNMN" "B_KLBSL_PNMN" ...
 $ AMP     : chr [1:403] "R" "R" "R" "R" ...
 $ AUG     : chr [1:403] "R" "R" "S" "R" ...
[etc]
```

If I rename the species column to 'mybugs', then the `mdro()` function works correctly.

**Comment by msberends** [comment]
Great! Many thanks for your reply.

I squashed the bug. For `mdro()` and `eucast_rules()`, the `col_mo` argument can now contain any column name of your data. The problem was that the column name that you picked was also present in the `microorganisms` data set, leading to conflicting code.

The development version nows contains the fix to this issue. If you like, you can try the latest version yourself using:

```r
install.packages("remotes") # if you haven't already
remotes::install_github("msberends/AMR")
```

**Comment by msberends** [comment]
### Fix released to official R repository
Just a small notice: we released a new software version, containing the fix to this issue. Please update your version using either the user interface of your software, or by running:
```r
install.packages("AMR")
```
