### ISSUE TITLE
convert to amr 1.6.0

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#39]
hai
Can you tell me how I can convert to amr version 1.6.0?
thanks

**Comment by msberends** [comment]
Hi! Sure, you mean to revert back to AMR 1.6.0?
Does v1.7.1 (the latest version) not offer what you like, or is it behaving unexpectedly? We are of course very curious to hear why the version you are using is not working well for you.

You can install a specific version using the `remotes` package:

```r
remotes::install_version("AMR", version = "1.6.0")
```

**Comment by ghost** [comment]
Thanks
problem solved. Just wanted to check something.   
the upgrade on  the first isolates is a good one!  (Implementation of methods, and deprecating the firstweighted option). Keep up the good work!

**Comment by msberends** [comment]
Alright! Thanks!
