### ISSUE TITLE
Custom_eucast_rules() and the use of antibiotic==NA before the tilde

### ISSUE THREAD

**Issue by mvrcwest** [msberends/AMR#40]
Hi again Matthijs

I hope everything is well.
After I had rewritten the eucast rules in the custom_eucast_rules(), I discovered that some of the rules were not applied. More specifically the expert rules were a problem. First i tried this syntax(just an example), which I think would be most logical since the custom_eucast_rules() works with just an antibiotic before and after the tilde:
genus == "Enterococcus faecium" ~ FUS=="R"
But it did not work. Then I tried:
genus == "Enterococcus faecium" & FUS==NA ~ FUS=="R"
which did not work either.
Do you have any workarounds or ideas on how to solve this one?

Kind regards
Marc Westerholt

**Comment by msberends** [comment]
Hi!

I think I understand why the rule is not working: you are testing for the *genus* "Enterococcus faecium", but that's not a genus, that's a full name. So it can probably solved with either:

```r
custom_eucast_rules(genus == "Enterococcus" & species == "faecium" ~ FUS == "R")
custom_eucast_rules(fullname == "Enterococcus faecium" ~ FUS == "R")
```

The first one is more robust, as it would also include subspecies (irrelevant for _E. faecalis_, but might be relevant for e.g., _Klebsiella_)

**Comment by msberends** [comment]
But it might be a good idea to build in a check, so the function would complain that in this case "Enterococcus faecium" is not a valid genus.

**Comment by mvrcwest** [comment]
How silly of me, but yes that would be a nice feature! Thank you for the help!
