### ISSUE TITLE
Mislabelled ATC code

### ISSUE THREAD

**Issue by rmartischang** [msberends/AMR#41]
when using the function ab_name() of AMR package on A07AA11 (ATC code) we get Retapamulin instead of Rifaximin. 

Ref: https://www.whocc.no/atc_ddd_index/

Many thanks

Romain

**Comment by msberends** [comment]
Thank you for using our package!

Great catch, we’ll fix it this or next week.

**Comment by msberends** [comment]
It seems some ATC codes were duplicated in the process of retrieving the codes from the WHOCC website, one of them being A07AA11:

```r
unique(antibiotics$atc[duplicated(antibiotics$atc)])
#> [1] NA        "J01DD09" "J01DD52" "J01DI01" "A07AA11"

antibiotics[which(antibiotics$atc == "A07AA11"), ]
#>       ab     atc     cid        name                group                atc_group1  atc_group2 abbreviations
#> 334  RTP A07AA11 6918462 Retapamulin Other antibacterials Intestinal antiinfectives Antibiotics              
#> 345  RFX A07AA11 6436173   Rifaximin Other antibacterials Intestinal antiinfectives Antibiotics              
#> 448 TYL1 A07AA11 6441094  Tylvalosin Other antibacterials Intestinal antiinfectives Antibiotics   
```

Both Retapamulin and Rifaximin erroneously have this ATC code in the `antibiotics` data set, and `as.ab()` (and for that reason, `ab_name()` too) just picks the first hit.

I need to look into the reason why some ATC codes are duplicated. To prevent this error in the future, we also need a unit test that checks if all ATC codes are unique. So:

* [x] Go over all ATC codes and make sure they match to the right drug
* [x] Fill in the fields `atc_group1` and `atc_group2` based on the right ATC codes
* [x] Add a unit test to prevent future errors to this end
