### ISSUE TITLE
Veillonella

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#47]
hai

I've noticed a small error: veillonella is a gram-negative coccoid bacterium.
AMR  mo_gramstain()  classifies it as a gram-positive coccus.
greetings!

**Comment by msberends** [comment]
I see. It’s a member of the phylum Firmicutes, whose members are considered Gram-positive. Except for the class Negativicutes which is part of the phylum. 

Thanks for the catch! We’ll update the `mo_gramstain()` function!
