### ISSUE TITLE
brmo() fills every row

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#49]
hai

i have a question regarding the BRMO() function:

it seems to ‘fill in’ every row with an answer (positive/negative). Even if all the antibiotic (rsi-class) columns are empty (NA).  Is that the correct behavior?

my code:
 
df <- df %>% mutate(BRMO_wip = brmo(., col_mo = "microbe_ID", only_rsi_columns = TRUE))     

Even with the last argument, every row (meaning every isolate) gets a value.

It would make more sense if the rows that contain empty antibiotic results get a NA while using the BRMO() function.
Now i get problems downstream when using the firstisolates() function. These empty rows are included because of this one column.

**Comment by msberends** [comment]
Thanks for raising this! We’ll look into it.

**Comment by msberends** [comment]
Found a solution, great issue!

All rows with `NA` in all analysed drugs will now return `NA` in any `mdro()` function, such as `brmo()`. Testing the new functionality now. Will be in the development version by tomorrow.

**Comment by ghost** [comment]
Thanks
When will the new version be released?

**Comment by msberends** [comment]
Good question :)
Probably in the next 4 weeks.

**Comment by ghost** [comment]
thanks!  can't wait  ;-)

**Comment by msberends** [comment]
We're waiting for this: https://www.eucast.org/clinical_breakpoints/

Hopefully we can add 12.0 early January, would be a pity not to include it if they almost release it!
