### ISSUE TITLE
small error in ab_property docs

### ISSUE THREAD

**Issue by ceefluz** [msberends/AMR#8]
Line 47 in `ab_property.Rd`:

`\item{x}{any (vector of) text that can be coerced to a valid microorganism code with \code{\link[=as.ab]{as.ab()}}}`

Should be `antibiotic` instead of `microorgansim`

**Comment by msberends** [comment]
Fixed in https://github.com/msberends/AMR/commit/c8edcb7439ba26b9a6be0fd1aada4ec7f3e6a0ed
