### ISSUE TITLE
EUCAST rules where there shouldn't be interpretations

### ISSUE THREAD

**Issue by theanita1** [msberends/AMR#94]
Hi Dr Matthijs

The EUCAST 2021 version has _Acinetobacter_ with no interpretation for cephalosporins, but when you run the RSI interpretation it produces interpretations. This is also true for ertapenem, aztreonam... I'm not sure if this is limited to just _Acinetobacter_ but this is the one that was flagged by my co-authors at this point

I'm currently using the coding "agar<- agar %>% mutate_if(is.mic, as.rsi, add_intrinsic_resistance = F)"

My current work around is to manually exclude the data in the cells (the data are direct exports from VITEK/Phoenix systems)

I understand that you are putting out a new version in the near future so wanted to flag this

**Comment by msberends** [comment]
Thanks for letting us know! 

The EUCAST clinical breakpoints reside to PK/PD rules if no specific rules for the genus/species are available. Might this be the reason?

I understand your co-authors too - perhaps it’s a good idea to add an `include_PKPD` argument and have it default to `FALSE`.

**Comment by msberends** [comment]
Now created it like this:

```r
as.rsi(as.mic(2), mo = "Acinetobacter", ab = "ceftriaxon", guideline = "EUCAST 2021")
#> => Interpreting MIC values of 'ceftriaxon' (CRO, ceftriaxone) according to EUCAST 2021... OK.
#> Class 'rsi'
#> [1] <NA>

as.rsi(as.mic(2), mo = "Acinetobacter", ab = "ceftriaxon", guideline = "EUCAST 2021", include_PKPD = TRUE)
#> => Interpreting MIC values of 'ceftriaxon' (CRO, ceftriaxone) according to EUCAST 2021... OK.
#> Class 'rsi'
#> [1] I
```

I will create a note as well to let users know that PK/PD rules were available but not applied, where this is the case.

**Comment by msberends** [comment]
The development version nows contains the fix to this issue. You can try the latest version yourself using:

```r
install.packages("remotes") # if you haven't already
remotes::install_github("msberends/AMR")
```
