### ISSUE TITLE
set body site for SIR intepretation

### ISSUE THREAD

**Issue by theanita1** [msberends/AMR#96]
Hi Dr Matthijs

I updated to the 1.8.2.9103 as suggested, and am liking the new features, but having a problem with the new assumption of body sites:

![image](https://user-images.githubusercontent.com/11519951/215393105-902c4fec-3318-4f92-80ca-341d2ca7fc1e.png)

My samples are not screening, but from bacteraemia. In this instance the R cut off is now at 1 (for screening) rather than at 2 (not screening)

I've already indicated that my isolates are not urine, but is there a way to indicate that they are all blood culture isolates?

Thanks

**Comment by theanita1** [comment]
Further on in the same as.sir interpretation with the same dataset, the packaged assumed unspecified rather than screen (which is correct in this instance, but why did it assume screen for one and not for the other?)
![image](https://user-images.githubusercontent.com/11519951/215398551-fcfbff4f-0936-4199-81e9-01ecdb1125df.png)

**Comment by msberends** [comment]
Hi,

Very good points you raise. We should have non-screen preferred over screen, but users should also be able to indicate this themselves. I'll think of a solution to allow this, great suggestion, many thanks!

**Comment by msberends** [comment]
For all your suggestions and package testing in the past months, we would also like to add you as a contributor to the package. Would you agree with this? There are no strings attached, it's just our 'acknowledgement' section 🙂

**Comment by theanita1** [comment]
Thank you Dr Matthijs, that would be a huge honour - was worried you and the team would be concerned with all my bug finding!

**Comment by msberends** [comment]
Not at all!! It's great to have you filing all those bugs! It's much appreciated 😃

Can I have your first and last name for the contributors list? You can also send me a direct message on Twitter (@msberends) or mail me at m.s.berends [at] umcg.nl. Many thanks!

**Comment by msberends** [comment]
I added `include_screening` to `as.sir()`, which defaults to `FALSE` but can be set with a global option as well.
