### ISSUE TITLE
strange results, when using first isolate()

### ISSUE THREAD

**Issue by ghost** [msberends/AMR#99]
-figured out the problem-
Please close this post  :-)

**Comment by msberends** [comment]
Ah, was just about to go check it 😄 

Was it not something that needs clarification in the documentation? We could also do that?

**Comment by ghost** [comment]
patientnumber should not be an integer when using firstisolate()
returns strange results, semi-correct, so takes a long time to find the problem...
as.character() fixed it.  

ps: next update almost ready?

**Comment by msberends** [comment]
Ah, so this is why I ask, that's a good addition which I immediately put in the package:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/31037261/224495073-0900b2b7-9248-4d5e-8c72-2a7d88b8dc8a.png">

This prevents your issues for other users in the future, thanks for letting me know!

Yes, almost done!
